import Sendov.FiniteRange.Basic
import Sendov.FiniteRange.Moments
import Sendov.FiniteRange.OddBound
import Sendov.FiniteRange.Reduce
import Sendov.FiniteRange.Degree5
import Sendov.FiniteRange.Degree6
import Sendov.FiniteRange.Degree7
import Sendov.FiniteRange.Degree8
import Sendov.FiniteRange.Degree20
